import "@/styles/globals.scss";
import Providers from "@/utils/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className="h-full">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
