import "@/styles/globals.scss";

import UserStoreInitializer from "@/components/UserStoreInitiliazer";
import Providers from "@/utils/provider";
import getUser from "@/api/userApi";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getUser();
  const user = data?.user;

  return (
    <html lang="en" className="h-full bg-white">
      <body className="h-full">
        <Providers>
          {user && <UserStoreInitializer user={user} />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
